### ISSUE TITLE
Infografía De Hilos

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/infografia-de-hilos-Jaczibeth#2]
[Infografía Hilos_Jaczibeth_Cruz.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Jaczibeth/files/15044464/Infografia.Hilos_Jaczibeth_Cruz.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rubrica tiene un 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
